export const tools = [
  {
    id: "base64",
    category: "developer",
    zh: "Base64 编解码",
    en: "Base64 codec",
    z: "文本与文件 · Base64 / URL-safe",
    e: "Text & files · Base64 / URL-safe",
    icon: "Braces",
    tag: "B64",
  },
  {
    id: "url",
    category: "developer",
    zh: "URL 编解码",
    en: "URL codec",
    z: "URI、组件和查询参数",
    e: "URIs, components & query parameters",
    icon: "Link",
    tag: "URL",
  },
  {
    id: "json",
    category: "developer",
    zh: "JSON 工作台",
    en: "JSON workspace",
    z: "校验、格式化与树状查看",
    e: "Validate, format & explore",
    icon: "Braces",
    tag: "{ }",
  },
  {
    id: "uuid",
    category: "developer",
    zh: "UUID 生成器",
    en: "UUID generator",
    z: "UUID v1 / v3 / v4 / v5 / v6 / v7",
    e: "UUID v1 / v3 / v4 / v5 / v6 / v7",
    icon: "Fingerprint",
    tag: "ID",
  },
  {
    id: "timestamp",
    category: "developer",
    zh: "时间戳转换",
    en: "Timestamp converter",
    z: "Unix 时间与带时区日期",
    e: "Unix timestamps & zoned dates",
    icon: "Clock",
    tag: "TIME",
  },
  {
    id: "hash",
    category: "developer",
    zh: "哈希与校验",
    en: "Hash & checksum",
    z: "MD5、SHA-1/2/3、BLAKE 与校验和",
    e: "MD5, SHA-1/2/3, BLAKE & checksums",
    icon: "Hash",
    tag: "SHA",
  },
  {
    id: "keys",
    category: "developer",
    zh: "密钥生成",
    en: "Key generator",
    z: "RSA、EC、Ed25519 与 X25519",
    e: "RSA, EC, Ed25519 & X25519",
    icon: "KeyRound",
    tag: "KEY",
  },
  {
    id: "signature",
    category: "developer",
    zh: "签名与验签",
    en: "Sign & verify",
    z: "内容签名、验证与密钥配对",
    e: "Signatures, verification & key matching",
    icon: "ShieldCheck",
    tag: "SIGN",
  },
  {
    id: "pdf-preview",
    category: "documents",
    zh: "PDF 预览",
    en: "PDF viewer",
    z: "浏览页面、尺寸和文档信息",
    e: "Browse pages, sizes & metadata",
    icon: "FileSearch",
    tag: "PDF",
  },
  {
    id: "pdf-merge",
    category: "documents",
    zh: "PDF 合并",
    en: "Merge PDFs",
    z: "自由排序，合并选定页面",
    e: "Combine selected pages in your order",
    icon: "Files",
    tag: "MERGE",
  },
  {
    id: "pdf-split",
    category: "documents",
    zh: "PDF 拆分与提取",
    en: "Split & extract PDF",
    z: "按范围、逐页或固定页数拆分",
    e: "Extract ranges or split into groups",
    icon: "Scissors",
    tag: "SPLIT",
  },
  {
    id: "pdf-organize",
    category: "documents",
    zh: "PDF 页面整理",
    en: "Organize PDF",
    z: "重排、旋转、复制和删除",
    e: "Reorder, rotate, duplicate & remove",
    icon: "LayoutGrid",
    tag: "PAGES",
  },
  {
    id: "images-pdf",
    category: "documents",
    zh: "图片转 PDF",
    en: "Images to PDF",
    z: "JPEG / PNG 合并为文档",
    e: "Turn JPEG & PNG images into a document",
    icon: "Image",
    tag: "IMG",
  },
  {
    id: "pdf-images",
    category: "documents",
    zh: "PDF 转图片",
    en: "PDF to images",
    z: "选页导出 PNG / JPEG / WebP",
    e: "Export pages as PNG, JPEG or WebP",
    icon: "ScanLine",
    tag: "EXPORT",
  },
  {
    id: "text",
    category: "documents",
    zh: "文本整理",
    en: "Text cleanup",
    z: "排序、去重、清理与统计",
    e: "Sort, deduplicate, clean & count",
    icon: "AlignLeft",
    tag: "TXT",
  },
] as const;
export type Tool = (typeof tools)[number];
