export const hashAlgorithms = [
  "MD5",
  "SHA-1",
  "SHA-224",
  "SHA-256",
  "SHA-384",
  "SHA-512",
  "SHA3-224",
  "SHA3-256",
  "SHA3-384",
  "SHA3-512",
  "Keccak-256",
  "BLAKE2b-512",
  "BLAKE2s-256",
  "BLAKE3-256",
  "RIPEMD-160",
  "SM3",
  "CRC32",
  "Adler-32",
];
export const defaults = {
  encoding: "utf-8",
  padding: "auto",
  wrap: 0,
  batch: false,
  jsonIndent: "2",
  jsonSort: false,
  jsonAscii: false,
  uuidVersion: "4",
  uuidNamespace: "dns",
  customNamespace: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
  uuidFormat: "standard",
  uuidUppercase: false,
  timezone: "local",
  hashFormat: "hex",
  inputFormat: "utf8",
  curve: "P-256",
  keyHash: "SHA-256",
  saltLength: 32,
  signatureEncoding: "base64",
  ecdsaFormat: "raw",
  normalization: "none",
  casing: "none",
  collapse: false,
  prefix: "",
  suffix: "",
};
export type ExtraConfig = typeof defaults;
